/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhansu_gui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author phanq
 */
public class frm_NV extends javax.swing.JFrame {

    private DSNV dsNhanViens;

    /**
     * Creates new form frm_NV
     */
    public frm_NV() {
        dsNhanViens = new DSNV();
        initComponents();
        tbNHV.setModel(new ModelData(dsNhanViens.ds));
        tbNHV.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgayVao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhuCap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtThucLinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayCong = new javax.swing.JTextField();
        cbBienChe = new javax.swing.JCheckBox();
        cbHopDong = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNHV = new javax.swing.JTable();
        btnReSet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ tên");

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày vào");

        txtNgayVao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayVaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Phụ cấp");

        jLabel4.setText("Mã nhân viên");

        jLabel5.setText("Thực lĩnh");

        txtThucLinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThucLinhActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        txtNgayCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayCongActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbBienChe);
        cbBienChe.setText("Biên chế");
        cbBienChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBienCheActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbHopDong);
        cbHopDong.setText("Hợp đồng");
        cbHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHopDongActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        tbNHV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbNHV);

        btnReSet.setText("Đặt lại");
        btnReSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtPhuCap)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(cbBienChe)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSua)
                                        .addComponent(cbHopDong)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTim)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                                .addComponent(txtThucLinh)
                                                .addComponent(txtNgayCong))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReSet)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtThucLinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBienChe)
                    .addComponent(cbHopDong)
                    .addComponent(btnReSet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnTim))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtNgayVaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayVaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayVaoActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Date ngayVao = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayVao = df.parse(txtNgayVao.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frm_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cbBienChe.isSelected()) {
            NHANVIEN nvbc = new BIENCHE(Integer.parseInt(txtNgayCong.getText()), txtMaNV.getText(), txtTenNV.getText(), ngayVao);
            dsNhanViens.Them(nvbc);
        } else {
            NHANVIEN nvhd = new HOPDONG(Integer.parseInt(txtNgayCong.getText()), txtMaNV.getText(), txtTenNV.getText(), ngayVao);
            dsNhanViens.Them(nvhd);
        }
        tbNHV.setModel(new ModelData(dsNhanViens.getDs()));
        tbNHV.repaint();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.dsNhanViens.Xoa(this.txtMaNV.getText());
        Setvaluenull();
        tbNHV.setModel(new ModelData(dsNhanViens.getDs()));
        tbNHV.repaint();

    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbBienCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBienCheActionPerformed
        // TODO add your handling code here:
        if (cbBienChe.isSelected()) {
            jLabel6.setText("Hệ số lương");
        }
    }//GEN-LAST:event_cbBienCheActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        NHANVIEN nv;
        Date ngayVao = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayVao = df.parse(txtNgayVao.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frm_NV.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cbBienChe.isSelected()) {
            nv = new BIENCHE(Double.parseDouble(txtNgayCong.getText()), txtMaNV.getText(), txtTenNV.getText(), ngayVao);
        } else {
            nv = new HOPDONG(Integer.parseInt(txtNgayCong.getText()), txtMaNV.getText(), txtTenNV.getText(), ngayVao);
        }
        this.dsNhanViens.Sua(nv);
        tbNHV.setModel(new ModelData(dsNhanViens.getDs()));
        tbNHV.repaint();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cbHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHopDongActionPerformed
        // TODO add your handling code here:
        if (cbHopDong.isSelected()) {
            jLabel6.setText("Ngày công");
        }

    }//GEN-LAST:event_cbHopDongActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        NHANVIEN nv = dsNhanViens.Tim(txtMaNV.getText());
        txtTenNV.setText(nv.getTenNV());
        txtMaNV.setText(nv.getMaNV());
        txtNgayVao.setText(nv.getNgayVao().toString());
        txtPhuCap.setText(String.valueOf(nv.PhuCap()));
        txtThucLinh.setText(String.valueOf(nv.ThucLinh()));
        if (nv instanceof BIENCHE) {
            BIENCHE bc = (BIENCHE) nv;
            txtNgayCong.setText(String.valueOf(bc.getHSL()));
        } else {
            HOPDONG hd = (HOPDONG) nv;
            txtNgayCong.setText(String.valueOf(hd.getSoNgayCong()));
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnReSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReSetActionPerformed
        // TODO add your handling code here:
        Setvaluenull();
    }//GEN-LAST:event_btnReSetActionPerformed

    private void txtNgayCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayCongActionPerformed

    private void txtThucLinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThucLinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThucLinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_NV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReSet;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBienChe;
    private javax.swing.JCheckBox cbHopDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNHV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayCong;
    private javax.swing.JTextField txtNgayVao;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThucLinh;
    // End of variables declaration//GEN-END:variables

    private void Setvaluenull() {
        txtMaNV.setText(null);
        txtTenNV.setText(null);
        txtNgayVao.setText(null);
        txtNgayCong.setText(null);
        txtPhuCap.setText(null);
        txtThucLinh.setText(null);
        cbBienChe.setSelected(false);
        cbHopDong.setSelected(false);
    }
}
