/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkhohang;

import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author phanq
 */
public class frmQLKHOHANG extends javax.swing.JFrame {

    private DSKHOHANG dsKhoHang;

    /**
     * Creates new form frmQLKHOHANG
     */
    public frmQLKHOHANG() {
        dsKhoHang = new DSKHOHANG();
        initComponents();
        tbXuat.setModel(new MODELDATA(dsKhoHang.list));
        tbXuat.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        txtNgayThue = new javax.swing.JTextField();
        txtTonKho = new javax.swing.JTextField();
        txtKhaNangChua = new javax.swing.JTextField();
        txtTenKhoHang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPhanTramGiamGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTienThue = new javax.swing.JTextField();
        lbKhoNL_KhoSP = new javax.swing.JLabel();
        txtKhoNL_KhoSP = new javax.swing.JTextField();
        cbKhoNguyenLieu = new javax.swing.JCheckBox();
        cbKhoSanPham = new javax.swing.JCheckBox();
        btnKhoTienThueLonNhat = new javax.swing.JButton();
        btnTongTienThue = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXuat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Quản lí kho hàng");

        jLabel1.setText("Tên kho hàng");

        jLabel2.setText("Khả năng chứa");

        jLabel3.setText("Tồn kho");

        jLabel4.setText("Ngày thuê");

        jLabel5.setText("Ngày trả");

        jLabel7.setText("Phần trăm giảm giá");

        txtPhanTramGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhanTramGiamGiaActionPerformed(evt);
            }
        });

        jLabel8.setText("Giảm giá");

        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });

        jLabel9.setText("Tiền thuê");

        lbKhoNL_KhoSP.setText("jLabel10");

        buttonGroup1.add(cbKhoNguyenLieu);
        cbKhoNguyenLieu.setText("Kho nguyên liệu");
        cbKhoNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhoNguyenLieuActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbKhoSanPham);
        cbKhoSanPham.setText("Kho sản phẩm");
        cbKhoSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhoSanPhamActionPerformed(evt);
            }
        });

        btnKhoTienThueLonNhat.setText("Kho có tiền thuê lớn nhất");
        btnKhoTienThueLonNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoTienThueLonNhatActionPerformed(evt);
            }
        });

        btnTongTienThue.setText("Tổng tiền thuê");
        btnTongTienThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongTienThueActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        tbXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbXuat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(lbKhoNL_KhoSP))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNgayTra, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addComponent(txtNgayThue)
                                                .addComponent(txtKhaNangChua, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtTonKho)
                                                .addComponent(txtTenKhoHang, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(txtKhoNL_KhoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtPhanTramGiamGia)
                                                    .addComponent(txtGiamGia)
                                                    .addComponent(txtTienThue, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                                            .addComponent(cbKhoNguyenLieu)
                                            .addComponent(cbKhoSanPham)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnDatLai, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnXoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCapNhat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnTimKiem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnKhoTienThueLonNhat)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnTongTienThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhanTramGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKhaNangChua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKhoSanPham)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbKhoNguyenLieu)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbKhoNL_KhoSP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKhoNL_KhoSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatLai)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoTienThueLonNhat)
                    .addComponent(btnTongTienThue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        // TODO add your handling code here:
        Setvaluenull();
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Date ngayThue = new Date();
        Date ngayTra = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayThue = df.parse(txtNgayThue.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frmQLKHOHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ngayTra = df.parse(txtNgayTra.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frmQLKHOHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cbKhoNguyenLieu.isSelected()) {
            KHOHANG knl = new KHONGUYENLIEU(txtKhoNL_KhoSP.getText(), txtTenKhoHang.getText(), Double.parseDouble(txtKhaNangChua.getText()), Double.parseDouble(txtTonKho.getText()), ngayThue, ngayTra);
            dsKhoHang.themKhoHang(knl);
        } else {
            KHOHANG ksp = new KHOSANPHAM(txtKhoNL_KhoSP.getText(), txtTenKhoHang.getText(), Double.parseDouble(txtKhaNangChua.getText()), Double.parseDouble(txtTonKho.getText()), ngayThue, ngayTra);
            dsKhoHang.themKhoHang(ksp);
        }
        tbXuat.setModel(new MODELDATA(dsKhoHang.getList()));
        tbXuat.repaint();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.dsKhoHang.xoa(this.txtTenKhoHang.getText());
        Setvaluenull();
        tbXuat.setModel(new MODELDATA(dsKhoHang.getList()));
        tbXuat.repaint();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbKhoNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhoNguyenLieuActionPerformed
        // TODO add your handling code here:
        if (cbKhoNguyenLieu.isSelected()) {
            lbKhoNL_KhoSP.setText("Tên nguyên liệu");
        }
    }//GEN-LAST:event_cbKhoNguyenLieuActionPerformed

    private void cbKhoSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhoSanPhamActionPerformed
        // TODO add your handling code here:
        if (cbKhoSanPham.isSelected()) {
            lbKhoNL_KhoSP.setText("Loại sản phẩm");
        }
    }//GEN-LAST:event_cbKhoSanPhamActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        KHOHANG kh;
        Date ngayThue = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayThue = df.parse(txtNgayThue.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frmQLKHOHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date ngayTra = new Date();
        try {
            ngayTra = df.parse(txtNgayTra.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frmQLKHOHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cbKhoNguyenLieu.isSelected()) {
            kh = new KHONGUYENLIEU(txtKhoNL_KhoSP.getText(), txtTenKhoHang.getText(), Double.parseDouble(txtKhaNangChua.getText()), Double.parseDouble(txtTonKho.getText()), ngayThue, ngayTra);
            dsKhoHang.themKhoHang(kh);
        } else {
            kh = new KHOSANPHAM(txtKhoNL_KhoSP.getText(), txtTenKhoHang.getText(), Double.parseDouble(txtKhaNangChua.getText()), Double.parseDouble(txtTonKho.getText()), ngayThue, ngayTra);
            dsKhoHang.themKhoHang(kh);
        }
        this.dsKhoHang.sua(kh);
        tbXuat.setModel(new MODELDATA(dsKhoHang.getList()));
        tbXuat.repaint();
    }//GEN-LAST:event_btnCapNhatActionPerformed

     public String convertDateToString(Date d){
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            return df.format(d);
        }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        KHOHANG kh = dsKhoHang.tim(txtTenKhoHang.getText());
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        String str1 = vn.format(kh.phanTramGiamGia());
        String str2 = vn.format(kh.TinhGiaGiam());
        String str3 = vn.format(kh.TinhTienThue());
        txtTenKhoHang.setText(kh.getTenKhoHang());
        txtKhaNangChua.setText(String.valueOf(kh.getKhaNangChua()));
        txtTonKho.setText(String.valueOf(kh.getTonKho()));
        txtNgayThue.setText(convertDateToString(kh.getNgayThue()));
        txtNgayTra.setText(convertDateToString(kh.getNgayTra()));
        txtPhanTramGiamGia.setText(str1);
        txtGiamGia.setText(str2);
        txtTienThue.setText(str3);
        if (kh instanceof KHOSANPHAM) {
            KHOSANPHAM ksp = (KHOSANPHAM) kh;
            txtKhoNL_KhoSP.setText(ksp.getLoaiSanPham());
        } else {
            KHONGUYENLIEU knl = (KHONGUYENLIEU) kh;
            txtKhoNL_KhoSP.setText(knl.getTenNguyenLieu());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtPhanTramGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhanTramGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhanTramGiamGiaActionPerformed

    private void btnKhoTienThueLonNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoTienThueLonNhatActionPerformed
        // TODO add your handling code here:
        KHOHANG kh = dsKhoHang.KhoHangMax();
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        String str1 = vn.format(kh.phanTramGiamGia());
        String str2 = vn.format(kh.TinhGiaGiam());
        String str3 = vn.format(kh.TinhTienThue());
        txtTenKhoHang.setText(kh.getTenKhoHang());
        txtKhaNangChua.setText(String.valueOf(kh.getKhaNangChua()));
        txtTonKho.setText(String.valueOf(kh.getTonKho()));
        txtNgayThue.setText(convertDateToString(kh.getNgayThue()));
        txtNgayTra.setText(convertDateToString(kh.getNgayTra()));
        txtPhanTramGiamGia.setText(str1);
        txtGiamGia.setText(str2);
        txtTienThue.setText(str3);
        if (kh instanceof KHOSANPHAM) {
            KHOSANPHAM ksp = (KHOSANPHAM) kh;
            txtKhoNL_KhoSP.setText(ksp.getLoaiSanPham());
        } else {
            KHONGUYENLIEU knl = (KHONGUYENLIEU) kh;
            txtKhoNL_KhoSP.setText(knl.getTenNguyenLieu());
        }
    }//GEN-LAST:event_btnKhoTienThueLonNhatActionPerformed

    private void btnTongTienThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongTienThueActionPerformed
        // TODO add your handling code here:
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        String str1 = vn.format(dsKhoHang.tongTienKhoNL());
        String str2 = vn.format(dsKhoHang.tongTienKhoSP());
        javax.swing.JOptionPane.showMessageDialog(this, "Tong tien thue kho nguyen lieu: " + str1 + "\nTong tien thue kho san pham: " + str2);

    }//GEN-LAST:event_btnTongTienThueActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtGiamGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLKHOHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLKHOHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLKHOHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLKHOHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLKHOHANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnKhoTienThueLonNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTongTienThue;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbKhoNguyenLieu;
    private javax.swing.JCheckBox cbKhoSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKhoNL_KhoSP;
    private javax.swing.JTable tbXuat;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtKhaNangChua;
    private javax.swing.JTextField txtKhoNL_KhoSP;
    private javax.swing.JTextField txtNgayThue;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtPhanTramGiamGia;
    private javax.swing.JTextField txtTenKhoHang;
    private javax.swing.JTextField txtTienThue;
    private javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables
 private void Setvaluenull() {
        txtTenKhoHang.setText(null);
        txtKhaNangChua.setText(null);
        txtTonKho.setText(null);
        txtNgayThue.setText(null);
        txtNgayTra.setText(null);
        txtPhanTramGiamGia.setText(null);
        txtGiamGia.setText(null);
        txtTienThue.setText(null);
        txtKhoNL_KhoSP.setText(null);
        cbKhoNguyenLieu.setSelected(false);
        cbKhoSanPham.setSelected(false);
    }
}
